import { db, schemesTable, jobsTable, assistanceCentersTable, activityTable } from "@workspace/db";
import { count } from "drizzle-orm";
import { logger } from "./logger";

export async function autoSeedIfEmpty() {
  try {
    const [schemeCount] = await db.select({ c: count() }).from(schemesTable);
    if ((schemeCount?.c ?? 0) > 0) {
      logger.info("Database already seeded, skipping auto-seed");
      return;
    }

    logger.info("Empty database detected — auto-seeding real data...");

    const schemes = [
      { name: "PM Awas Yojana – Gramin (PMAY-G)", nameHindi: "प्रधानमंत्री आवास योजना – ग्रामीण", description: "Housing for All scheme providing financial assistance for construction of pucca houses to all homeless and those living in kutcha/dilapidated houses in rural areas.", descriptionHindi: "सभी बेघर लोगों और ग्रामीण क्षेत्रों में कच्चे/जर्जर घरों में रहने वालों को पक्के घर निर्माण के लिए वित्तीय सहायता प्रदान करने की आवास सभी के लिए योजना।", schemeType: "housing", category: "all", minAge: 18, maxAge: null, maxIncome: 300000, ministry: "Ministry of Rural Development", benefitAmount: "Up to Rs. 1,20,000 (plain areas) / Rs. 1,30,000 (hilly/NE states)", applicationUrl: "https://pmayg.nic.in", documents: ["Aadhar Card", "BPL Certificate", "Bank Account Details", "Land Ownership Proof", "Caste Certificate (if applicable)"], isActive: true },
      { name: "PM Awas Yojana – Urban (PMAY-U)", nameHindi: "प्रधानमंत्री आवास योजना – शहरी", description: "Credit-linked subsidy scheme for urban poor to access affordable housing. Provides interest subsidy on home loans for EWS, LIG, and MIG categories.", descriptionHindi: "शहरी गरीबों को किफायती आवास तक पहुंचने के लिए क्रेडिट-लिंक्ड सब्सिडी योजना। ईडब्ल्यूएस, एलआईजी और एमआईजी श्रेणियों के लिए होम लोन पर ब्याज सब्सिडी प्रदान करती है।", schemeType: "housing", category: "all", minAge: 18, maxAge: null, maxIncome: 1800000, ministry: "Ministry of Housing and Urban Affairs", benefitAmount: "Interest subsidy up to Rs. 2.67 lakh", applicationUrl: "https://pmaymis.gov.in", documents: ["Aadhar Card", "Income Certificate", "Property Documents", "Bank Statement"], isActive: true },
      { name: "PM Kisan Samman Nidhi (PM-KISAN)", nameHindi: "प्रधानमंत्री किसान सम्मान निधि", description: "Direct income support of Rs. 6000 per year to small and marginal farmer families across India in three equal installments of Rs. 2000 each.", descriptionHindi: "छोटे और सीमांत किसान परिवारों को Rs. 2000 की तीन समान किस्तों में प्रति वर्ष Rs. 6000 की प्रत्यक्ष आय सहायता।", schemeType: "employment", category: "all", minAge: 18, maxAge: null, maxIncome: 200000, ministry: "Ministry of Agriculture & Farmers Welfare", benefitAmount: "Rs. 6,000 per year (Rs. 2,000 per installment)", applicationUrl: "https://pmkisan.gov.in", documents: ["Aadhar Card", "Land Records (Khasra/Khatauni)", "Bank Account Details"], isActive: true },
      { name: "Ayushman Bharat – PM Jan Arogya Yojana (PMJAY)", nameHindi: "आयुष्मान भारत – प्रधानमंत्री जन आरोग्य योजना", description: "World's largest health insurance scheme providing Rs. 5 lakh per family per year for secondary and tertiary care hospitalization to 10+ crore poor and vulnerable families.", descriptionHindi: "10 करोड़ से अधिक गरीब और कमजोर परिवारों को द्वितीयक और तृतीयक देखभाल अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष Rs. 5 लाख प्रदान करने वाली विश्व की सबसे बड़ी स्वास्थ्य बीमा योजना।", schemeType: "health", category: "all", minAge: null, maxAge: null, maxIncome: 200000, ministry: "Ministry of Health and Family Welfare", benefitAmount: "Rs. 5 lakh per family per year", applicationUrl: "https://pmjay.gov.in", documents: ["Aadhar Card", "Ration Card", "BPL Certificate or SECC Data"], isActive: true },
      { name: "National Scholarship Portal (NSP)", nameHindi: "राष्ट्रीय छात्रवृत्ति पोर्टल", description: "Centralized portal for scholarships from various government ministries for SC, ST, OBC, minority, and economically weaker section students from Class 1 to PhD level.", descriptionHindi: "कक्षा 1 से पीएचडी स्तर तक एससी, एसटी, ओबीसी, अल्पसंख्यक और आर्थिक रूप से कमजोर वर्ग के छात्रों के लिए विभिन्न सरकारी मंत्रालयों की छात्रवृत्ति का केंद्रीकृत पोर्टल।", schemeType: "scholarship", category: "all", minAge: 6, maxAge: 35, maxIncome: 250000, ministry: "Ministry of Electronics and IT", benefitAmount: "Varies by scholarship – Rs. 500 to Rs. 50,000 per year", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "Marksheet", "Income Certificate", "Caste Certificate", "Bank Account Details"], isActive: true },
      { name: "SC Post Matric Scholarship", nameHindi: "अनुसूचित जाति पोस्ट मैट्रिक छात्रवृत्ति", description: "Scholarship for Scheduled Caste students studying at post-matriculation or post-secondary stage to enable them to complete their education.", descriptionHindi: "मैट्रिकोत्तर या माध्यमिकोत्तर स्तर पर पढ़ने वाले अनुसूचित जाति के छात्रों को उनकी शिक्षा पूरी करने में सक्षम बनाने के लिए छात्रवृत्ति।", schemeType: "scholarship", category: "sc", minAge: 14, maxAge: 35, maxIncome: 250000, ministry: "Ministry of Social Justice and Empowerment", benefitAmount: "Maintenance allowance + tuition fees (varies by course)", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "Caste Certificate", "Income Certificate", "Marksheet", "Institution Certificate"], isActive: true },
      { name: "ST Scholarship – Pre & Post Matric", nameHindi: "अनुसूचित जनजाति छात्रवृत्ति – प्री और पोस्ट मैट्रिक", description: "Scholarship for Scheduled Tribe students from Class 9 onwards including higher education to reduce dropout rates and improve educational attainment.", descriptionHindi: "छात्रों के बाहर निकलने की दर को कम करने और शैक्षिक उपलब्धि में सुधार के लिए कक्षा 9 से आगे उच्च शिक्षा सहित अनुसूचित जनजाति के छात्रों के लिए छात्रवृत्ति।", schemeType: "scholarship", category: "st", minAge: 14, maxAge: 35, maxIncome: 250000, ministry: "Ministry of Tribal Affairs", benefitAmount: "Maintenance allowance + non-refundable fees", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "Tribal Certificate", "Income Certificate", "Marksheet"], isActive: true },
      { name: "OBC Pre-Matric Scholarship", nameHindi: "ओबीसी प्री-मैट्रिक छात्रवृत्ति", description: "Scholarship for OBC students studying in Class 1 to 10 to support their education and reduce family financial burden.", descriptionHindi: "कक्षा 1 से 10 में पढ़ने वाले ओबीसी छात्रों को उनकी शिक्षा में सहायता देने और परिवार पर वित्तीय बोझ कम करने के लिए छात्रवृत्ति।", schemeType: "scholarship", category: "obc", minAge: 6, maxAge: 18, maxIncome: 100000, ministry: "Ministry of Social Justice and Empowerment", benefitAmount: "Rs. 750 to Rs. 1,500 per month", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "OBC Certificate", "Income Certificate", "School Certificate"], isActive: true },
      { name: "PM Matru Vandana Yojana (PMMVY)", nameHindi: "प्रधानमंत्री मातृत्व वंदना योजना", description: "Maternity benefit scheme providing Rs. 5,000 to pregnant and lactating mothers for first live birth to compensate for wage loss and improve health-seeking behaviour.", descriptionHindi: "पहले जीवित जन्म के लिए गर्भवती और स्तनपान कराने वाली माताओं को Rs. 5,000 प्रदान करने की मातृत्व लाभ योजना।", schemeType: "health", category: "women", minAge: 18, maxAge: 45, maxIncome: 200000, ministry: "Ministry of Women and Child Development", benefitAmount: "Rs. 5,000 in installments", applicationUrl: "https://pmmvy.wcd.gov.in", documents: ["Aadhar Card", "Bank Account Details", "Mother and Child Protection Card", "Marriage Certificate"], isActive: true },
      { name: "Divyangjan Scholarship Scheme", nameHindi: "दिव्यांगजन छात्रवृत्ति योजना", description: "Scholarship for persons with disabilities studying at pre-matric, post-matric level and pursuing higher education including ITI, polytechnic, and professional courses.", descriptionHindi: "प्री-मैट्रिक, पोस्ट-मैट्रिक स्तर पर और आईटीआई, पॉलिटेक्निक और व्यावसायिक पाठ्यक्रमों सहित उच्च शिक्षा प्राप्त करने वाले दिव्यांग व्यक्तियों के लिए छात्रवृत्ति।", schemeType: "scholarship", category: "disability", minAge: 5, maxAge: 35, maxIncome: 250000, ministry: "Ministry of Social Justice and Empowerment", benefitAmount: "Rs. 500 to Rs. 3,500 per month based on level", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "Disability Certificate (40%+ disability)", "Income Certificate", "Marksheet"], isActive: true },
      { name: "MNREGA – Mahatma Gandhi NREGS", nameHindi: "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी योजना", description: "Legal guarantee of 100 days of wage employment per financial year to every rural household whose adult members volunteer to do unskilled manual work.", descriptionHindi: "प्रत्येक ग्रामीण परिवार जिसके वयस्क सदस्य अकुशल शारीरिक कार्य करने के लिए स्वयंसेवी हों, उन्हें प्रति वित्तीय वर्ष 100 दिनों के मजदूरी रोजगार की कानूनी गारंटी।", schemeType: "employment", category: "all", minAge: 18, maxAge: null, maxIncome: 100000, ministry: "Ministry of Rural Development", benefitAmount: "Rs. 220–320 per day (state-wise wage rates)", applicationUrl: "https://nrega.nic.in", documents: ["Aadhar Card", "Job Card (from Gram Panchayat)", "Bank Account / Post Office Account"], isActive: true },
      { name: "Sukanya Samriddhi Yojana", nameHindi: "सुकन्या समृद्धि योजना", description: "Small savings scheme for girl child, opened by parents/guardians for girls below 10 years. Provides highest interest rate among small savings schemes (8.2% p.a.)", descriptionHindi: "बालिकाओं के लिए छोटी बचत योजना, माता-पिता/अभिभावकों द्वारा 10 वर्ष से कम उम्र की बालिकाओं के लिए खोली जाती है।", schemeType: "scholarship", category: "women", minAge: null, maxAge: 10, maxIncome: null, ministry: "Ministry of Finance", benefitAmount: "8.2% p.a. interest + tax benefits under 80C", applicationUrl: "https://www.indiapost.gov.in", documents: ["Aadhar Card (Parent)", "Birth Certificate of Girl Child", "Address Proof"], isActive: true },
      { name: "Atal Pension Yojana (APY)", nameHindi: "अटल पेंशन योजना", description: "Government-backed pension scheme for workers in unorganised sector. Subscribers receive a fixed pension of Rs. 1,000 to Rs. 5,000 per month at age 60.", descriptionHindi: "असंगठित क्षेत्र के श्रमिकों के लिए सरकार समर्थित पेंशन योजना।", schemeType: "pension", category: "all", minAge: 18, maxAge: 40, maxIncome: 200000, ministry: "Ministry of Finance", benefitAmount: "Rs. 1,000 to Rs. 5,000 per month pension at age 60", applicationUrl: "https://npscra.nsdl.co.in", documents: ["Aadhar Card", "Bank Account Details", "Mobile Number"], isActive: true },
      { name: "PM Jeevan Jyoti Bima Yojana (PMJJBY)", nameHindi: "प्रधानमंत्री जीवन ज्योति बीमा योजना", description: "Life insurance scheme offering Rs. 2 lakh death benefit for a premium of only Rs. 436 per year for people aged 18–55 with a bank account.", descriptionHindi: "18-55 वर्ष के बैंक खाता धारकों के लिए केवल Rs. 436 प्रति वर्ष के प्रीमियम पर Rs. 2 लाख का मृत्यु लाभ प्रदान करने वाली जीवन बीमा योजना।", schemeType: "other", category: "all", minAge: 18, maxAge: 55, maxIncome: 200000, ministry: "Ministry of Finance", benefitAmount: "Rs. 2 lakh on death", applicationUrl: "https://jansuraksha.gov.in", documents: ["Aadhar Card", "Bank Account Details"], isActive: true },
      { name: "PM Suraksha Bima Yojana (PMSBY)", nameHindi: "प्रधानमंत्री सुरक्षा बीमा योजना", description: "Accident insurance scheme providing Rs. 2 lakh for accidental death/full disability at a very low premium of Rs. 20 per year for ages 18–70.", descriptionHindi: "18-70 वर्ष के आयु वर्ग के लिए मात्र Rs. 20 प्रति वर्ष के प्रीमियम पर आकस्मिक मृत्यु/पूर्ण विकलांगता के लिए Rs. 2 लाख प्रदान करने वाली दुर्घटना बीमा योजना।", schemeType: "other", category: "all", minAge: 18, maxAge: 70, maxIncome: 200000, ministry: "Ministry of Finance", benefitAmount: "Rs. 2 lakh on accidental death/full disability", applicationUrl: "https://jansuraksha.gov.in", documents: ["Aadhar Card", "Bank Account Details"], isActive: true },
      { name: "PM Mudra Yojana (PMMY)", nameHindi: "प्रधानमंत्री मुद्रा योजना", description: "Provides loans up to Rs. 10 lakh to non-corporate, non-farm small/micro enterprises through Shishu, Kishor, and Tarun categories.", descriptionHindi: "शिशु, किशोर और तरुण श्रेणियों के माध्यम से गैर-कॉर्पोरेट, गैर-कृषि लघु/सूक्ष्म उद्यमों को Rs. 10 लाख तक का ऋण प्रदान करता है।", schemeType: "employment", category: "all", minAge: 18, maxAge: null, maxIncome: 500000, ministry: "Ministry of Finance", benefitAmount: "Loans up to Rs. 10 lakh at low interest rates", applicationUrl: "https://mudra.org.in", documents: ["Aadhar Card", "PAN Card", "Business Plan", "Bank Statement", "Proof of Business"], isActive: true },
      { name: "Stand-Up India Scheme", nameHindi: "स्टैंड-अप इंडिया योजना", description: "Facilitates bank loans between Rs. 10 lakh and Rs. 1 crore to SC/ST and women borrowers for setting up a greenfield enterprise.", descriptionHindi: "SC/ST और महिला उद्यमियों को Rs. 10 लाख से Rs. 1 करोड़ तक का ऋण प्रदान करती है।", schemeType: "employment", category: "sc", minAge: 18, maxAge: null, maxIncome: null, ministry: "Ministry of Finance", benefitAmount: "Bank loans from Rs. 10 lakh to Rs. 1 crore", applicationUrl: "https://www.standupmitra.in", documents: ["Aadhar Card", "PAN Card", "Business Plan", "Bank Statement", "Caste Certificate (for SC/ST)"], isActive: true },
      { name: "PM Ujjwala Yojana (PMUY)", nameHindi: "प्रधानमंत्री उज्ज्वला योजना", description: "Provides free LPG gas connections to women from BPL households to replace unhealthy cooking fuels and reduce indoor air pollution.", descriptionHindi: "अस्वास्थ्यकर खाना पकाने के ईंधन को बदलने के लिए बीपीएल परिवारों की महिलाओं को मुफ्त एलपीजी गैस कनेक्शन प्रदान करती है।", schemeType: "other", category: "women", minAge: 18, maxAge: null, maxIncome: 100000, ministry: "Ministry of Petroleum and Natural Gas", benefitAmount: "Free LPG connection + subsidy on refills", applicationUrl: "https://pmuy.gov.in", documents: ["Aadhar Card", "BPL Certificate or Ration Card", "Bank Account Details"], isActive: true },
      { name: "Beti Bachao Beti Padhao", nameHindi: "बेटी बचाओ बेटी पढ़ाओ", description: "Addresses declining Child Sex Ratio and promotes welfare and education of girl child through prevention of gender-biased sex selective elimination.", descriptionHindi: "बालिकाओं के कल्याण और शिक्षा को बढ़ावा देने के लिए लिंग आधारित चुनिंदा उन्मूलन की रोकथाम।", schemeType: "scholarship", category: "women", minAge: null, maxAge: 18, maxIncome: null, ministry: "Ministry of Women and Child Development", benefitAmount: "Benefits under Sukanya Samriddhi + conditional cash transfers", applicationUrl: "https://wcd.nic.in", documents: ["Birth Certificate of Girl Child", "Aadhar Card"], isActive: true },
      { name: "PM Fasal Bima Yojana (PMFBY)", nameHindi: "प्रधानमंत्री फसल बीमा योजना", description: "Crop insurance scheme providing financial support to farmers who suffer crop loss/damage due to unforeseen events like natural calamities, pests, and diseases.", descriptionHindi: "प्राकृतिक आपदाओं, कीटों और बीमारियों जैसी अप्रत्याशित घटनाओं के कारण फसल हानि/क्षति झेलने वाले किसानों को वित्तीय सहायता प्रदान करने वाली फसल बीमा योजना।", schemeType: "other", category: "all", minAge: 18, maxAge: null, maxIncome: null, ministry: "Ministry of Agriculture & Farmers Welfare", benefitAmount: "Full insured sum for crop loss (varies by crop)", applicationUrl: "https://pmfby.gov.in", documents: ["Aadhar Card", "Land Records", "Bank Account Details", "Sowing Certificate"], isActive: true },
      { name: "Kisan Credit Card (KCC)", nameHindi: "किसान क्रेडिट कार्ड", description: "Provides farmers adequate and timely credit to meet agricultural needs at affordable interest rates.", descriptionHindi: "किसानों को किफायती ब्याज दरों पर कृषि आवश्यकताओं को पूरा करने के लिए पर्याप्त और समय पर ऋण प्रदान करता है।", schemeType: "employment", category: "all", minAge: 18, maxAge: null, maxIncome: null, ministry: "Ministry of Agriculture & Farmers Welfare", benefitAmount: "Credit limit based on landholding + 2% interest subvention", applicationUrl: "https://www.nabard.org", documents: ["Aadhar Card", "Land Records", "PAN Card or Voter ID", "Passport Photo"], isActive: true },
      { name: "Indira Gandhi National Old Age Pension (IGNOAPS)", nameHindi: "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन", description: "Monthly pension of Rs. 200–500 to BPL elderly persons aged 60 years and above.", descriptionHindi: "60 वर्ष और उससे अधिक आयु के बीपीएल बुजुर्गों को Rs. 200–500 मासिक पेंशन।", schemeType: "pension", category: "all", minAge: 60, maxAge: null, maxIncome: 100000, ministry: "Ministry of Rural Development", benefitAmount: "Rs. 200 per month (60-79 yrs) / Rs. 500 per month (80+ yrs)", applicationUrl: "https://nsap.nic.in", documents: ["Aadhar Card", "Age Proof", "BPL Certificate", "Bank Account Details"], isActive: true },
      { name: "Indira Gandhi National Widow Pension (IGNWPS)", nameHindi: "इंदिरा गांधी राष्ट्रीय विधवा पेंशन", description: "Monthly pension of Rs. 300 to widows aged 40–79 years from BPL households.", descriptionHindi: "बीपीएल परिवारों की 40-79 वर्ष आयु की विधवाओं को Rs. 300 मासिक पेंशन।", schemeType: "pension", category: "women", minAge: 40, maxAge: 79, maxIncome: 100000, ministry: "Ministry of Rural Development", benefitAmount: "Rs. 300 per month", applicationUrl: "https://nsap.nic.in", documents: ["Aadhar Card", "Husband's Death Certificate", "BPL Certificate", "Bank Account Details"], isActive: true },
      { name: "Indira Gandhi National Disability Pension (IGNDPS)", nameHindi: "इंदिरा गांधी राष्ट्रीय दिव्यांगजन पेंशन", description: "Monthly pension of Rs. 300 to severely/multiple disabled persons aged 18–79 years from BPL households.", descriptionHindi: "बीपीएल परिवारों के 18-79 वर्ष आयु के गंभीर/बहुविकलांग व्यक्तियों को Rs. 300 मासिक पेंशन।", schemeType: "pension", category: "disability", minAge: 18, maxAge: 79, maxIncome: 100000, ministry: "Ministry of Rural Development", benefitAmount: "Rs. 300 per month", applicationUrl: "https://nsap.nic.in", documents: ["Aadhar Card", "Disability Certificate (80%+ disability)", "BPL Certificate", "Bank Account Details"], isActive: true },
      { name: "PM SVANidhi – Street Vendor Loan", nameHindi: "पीएम स्वनिधि – स्ट्रीट वेंडर लोन", description: "Micro-credit scheme for street vendors providing collateral-free working capital loans starting from Rs. 10,000.", descriptionHindi: "स्ट्रीट वेंडर्स के लिए Rs. 10,000 से शुरू होने वाले बिना गारंटी के वर्किंग कैपिटल ऋण।", schemeType: "employment", category: "all", minAge: 18, maxAge: null, maxIncome: 200000, ministry: "Ministry of Housing and Urban Affairs", benefitAmount: "Rs. 10,000 (1st loan) → Rs. 20,000 → Rs. 50,000", applicationUrl: "https://pmsvanidhi.mohua.gov.in", documents: ["Aadhar Card", "Vending Certificate or Letter of Recommendation", "Bank Account Details"], isActive: true },
      { name: "PM Jan Dhan Yojana (PMJDY)", nameHindi: "प्रधानमंत्री जन धन योजना", description: "National mission on financial inclusion providing universal access to banking with zero balance accounts, RuPay debit card, and Rs. 2 lakh accident insurance.", descriptionHindi: "बैंकिंग तक सार्वभौमिक पहुंच प्रदान करने वाला वित्तीय समावेशन पर राष्ट्रीय मिशन।", schemeType: "other", category: "all", minAge: 10, maxAge: null, maxIncome: 200000, ministry: "Ministry of Finance", benefitAmount: "Zero balance account + Rs. 2 lakh accident cover + overdraft up to Rs. 10,000", applicationUrl: "https://pmjdy.gov.in", documents: ["Aadhar Card", "Passport Photo"], isActive: true },
      { name: "Merit-cum-Means Scholarship for Minorities", nameHindi: "अल्पसंख्यकों के लिए मेरिट-कम-मीन्स छात्रवृत्ति", description: "Scholarship for students from minority communities pursuing professional and technical courses at graduate/postgraduate level.", descriptionHindi: "स्नातक/स्नातकोत्तर स्तर पर व्यावसायिक और तकनीकी पाठ्यक्रम करने वाले अल्पसंख्यक समुदाय के छात्रों के लिए छात्रवृत्ति।", schemeType: "scholarship", category: "minority", minAge: 17, maxAge: 35, maxIncome: 250000, ministry: "Ministry of Minority Affairs", benefitAmount: "Rs. 20,000 per year (course fee) + Rs. 10,000 maintenance", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "Minority Certificate", "Income Certificate", "Marksheet", "Admission Certificate"], isActive: true },
      { name: "Maulana Azad National Fellowship (MANF)", nameHindi: "मौलाना आजाद राष्ट्रीय फेलोशिप", description: "Fellowship for minority students pursuing M.Phil and Ph.D level education.", descriptionHindi: "एम.फिल और पीएचडी स्तर की शिक्षा प्राप्त करने वाले अल्पसंख्यक छात्रों के लिए फेलोशिप।", schemeType: "scholarship", category: "minority", minAge: 21, maxAge: 35, maxIncome: 250000, ministry: "Ministry of Minority Affairs", benefitAmount: "JRF: Rs. 31,000/month; SRF: Rs. 35,000/month", applicationUrl: "https://ugc.ac.in", documents: ["Aadhar Card", "Minority Certificate", "UGC NET/JRF Certificate", "Postgraduate Marksheet"], isActive: true },
      { name: "PM Kisan Maan Dhan Yojana", nameHindi: "प्रधानमंत्री किसान मान धन योजना", description: "Voluntary and contributory pension scheme for small and marginal farmers aged 18–40 years providing Rs. 3,000 monthly pension after age 60.", descriptionHindi: "18-40 वर्ष आयु के छोटे और सीमांत किसानों के लिए स्वैच्छिक और अंशदायी पेंशन योजना।", schemeType: "pension", category: "all", minAge: 18, maxAge: 40, maxIncome: 150000, ministry: "Ministry of Agriculture & Farmers Welfare", benefitAmount: "Rs. 3,000 per month after age 60", applicationUrl: "https://pmkmy.gov.in", documents: ["Aadhar Card", "Land Records", "Bank Account Details", "IFSC Code"], isActive: true },
      { name: "Rashtriya Vayoshri Yojana", nameHindi: "राष्ट्रीय वयोश्री योजना", description: "Provides free assistive devices to senior citizens with disabilities from BPL households.", descriptionHindi: "बीपीएल परिवारों के विकलांग वरिष्ठ नागरिकों को मुफ्त सहायक उपकरण प्रदान करती है।", schemeType: "other", category: "disability", minAge: 60, maxAge: null, maxIncome: 100000, ministry: "Ministry of Social Justice and Empowerment", benefitAmount: "Free assistive devices worth Rs. 5,000–10,000", applicationUrl: "https://alimco.in", documents: ["Aadhar Card", "Age Proof", "BPL Certificate", "Disability Certificate"], isActive: true },
      { name: "Aajeevika – National Rural Livelihoods Mission", nameHindi: "आजीविका – राष्ट्रीय ग्रामीण आजीविका मिशन", description: "Poverty alleviation programme promoting self-employment through Self Help Groups of rural poor women.", descriptionHindi: "ग्रामीण गरीब महिलाओं के स्वयं सहायता समूहों के माध्यम से स्वरोजगार को बढ़ावा देने वाला गरीबी उन्मूलन कार्यक्रम।", schemeType: "employment", category: "women", minAge: 18, maxAge: null, maxIncome: 100000, ministry: "Ministry of Rural Development", benefitAmount: "Rs. 15,000 revolving fund per SHG + bank linkage", applicationUrl: "https://aajeevika.gov.in", documents: ["Aadhar Card", "SHG Membership", "Bank Account Details"], isActive: true },
      { name: "PM Vishwakarma Yojana", nameHindi: "प्रधानमंत्री विश्वकर्मा योजना", description: "Support for traditional artisans and craftspeople through skill training, modern tools, and collateral-free loans at 5% interest.", descriptionHindi: "कौशल प्रशिक्षण, आधुनिक उपकरणों और 5% ब्याज पर बिना गारंटी ऋण के माध्यम से पारंपरिक कारीगरों को सहायता।", schemeType: "employment", category: "all", minAge: 18, maxAge: null, maxIncome: 300000, ministry: "Ministry of Micro, Small and Medium Enterprises", benefitAmount: "Rs. 1 lakh (1st loan) + Rs. 2 lakh (2nd loan) at 5% interest + Rs. 15,000 toolkit", applicationUrl: "https://pmvishwakarma.gov.in", documents: ["Aadhar Card", "Proof of Trade (artisan certificate)", "Bank Account Details"], isActive: true },
      { name: "National Food Security Act – NFSA (PDS)", nameHindi: "राष्ट्रीय खाद्य सुरक्षा अधिनियम – एनएफएसए", description: "Legal right to subsidized food grains under the Public Distribution System for BPL families.", descriptionHindi: "बीपीएल परिवारों के लिए सार्वजनिक वितरण प्रणाली के तहत सब्सिडीयुक्त खाद्यान्न का कानूनी अधिकार।", schemeType: "food", category: "all", minAge: null, maxAge: null, maxIncome: 100000, ministry: "Ministry of Consumer Affairs, Food and Public Distribution", benefitAmount: "5 kg food grain per person per month at subsidized rates", applicationUrl: null, documents: ["Ration Card", "Aadhar Card"], isActive: true },
      { name: "PM Poshan Abhiyan (Mid-Day Meal)", nameHindi: "प्रधानमंत्री पोषण अभियान (मध्याह्न भोजन)", description: "Provides free cooked meals to students studying in Classes 1–8 in government schools.", descriptionHindi: "सरकारी स्कूलों में कक्षा 1-8 में पढ़ने वाले छात्रों को मुफ्त पका हुआ भोजन प्रदान करता है।", schemeType: "food", category: "all", minAge: 6, maxAge: 14, maxIncome: null, ministry: "Ministry of Education", benefitAmount: "Free nutritious meals on school days", applicationUrl: null, documents: ["School Enrollment Certificate"], isActive: true },
      { name: "Pradhan Mantri Gram Sadak Yojana (PMGSY)", nameHindi: "प्रधानमंत्री ग्राम सड़क योजना", description: "All-weather road connectivity to unconnected habitations in rural areas.", descriptionHindi: "ग्रामीण क्षेत्रों में असंपर्कित बस्तियों को सर्वमौसमी सड़क संपर्क।", schemeType: "other", category: "all", minAge: null, maxAge: null, maxIncome: null, ministry: "Ministry of Rural Development", benefitAmount: "Infrastructure development (community benefit)", applicationUrl: "https://pmgsy.nic.in", documents: [], isActive: true },
      { name: "PM Shram Yogi Maan-dhan (PM-SYM)", nameHindi: "प्रधानमंत्री श्रम योगी मान-धन", description: "Voluntary pension scheme for unorganised sector workers earning below Rs. 15,000 per month.", descriptionHindi: "Rs. 15,000 प्रति माह से कम कमाने वाले असंगठित क्षेत्र के श्रमिकों के लिए पेंशन योजना।", schemeType: "pension", category: "all", minAge: 18, maxAge: 40, maxIncome: 180000, ministry: "Ministry of Labour and Employment", benefitAmount: "Rs. 3,000 per month pension at age 60", applicationUrl: "https://labour.gov.in", documents: ["Aadhar Card", "Bank Account / Jan Dhan Account", "Mobile Number"], isActive: true },
      { name: "National Apprenticeship Promotion Scheme (NAPS)", nameHindi: "राष्ट्रीय शिक्षुता प्रोत्साहन योजना", description: "Stipend support for apprentices in industry. Government shares 25% of stipend with employer.", descriptionHindi: "उद्योग में प्रशिक्षुओं को वजीफा सहायता।", schemeType: "employment", category: "all", minAge: 14, maxAge: 35, maxIncome: 200000, ministry: "Ministry of Skill Development and Entrepreneurship", benefitAmount: "Stipend support + skill training + job placement", applicationUrl: "https://apprenticeshipindia.gov.in", documents: ["Aadhar Card", "Educational Qualification Certificate", "Bank Account Details"], isActive: true },
      { name: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)", nameHindi: "प्रधानमंत्री कौशल विकास योजना", description: "Free short-term skill training aligned to National Skills Qualification Framework with monetary reward on certification.", descriptionHindi: "प्रमाणन पर मौद्रिक पुरस्कार के साथ मुफ्त अल्पकालिक कौशल प्रशिक्षण।", schemeType: "employment", category: "all", minAge: 15, maxAge: 45, maxIncome: 200000, ministry: "Ministry of Skill Development and Entrepreneurship", benefitAmount: "Free training + Rs. 8,000 monetary reward on certification", applicationUrl: "https://pmkvyofficial.org", documents: ["Aadhar Card", "Educational Qualification Certificate", "Bank Account Details"], isActive: true },
      { name: "SC Pre-Matric Scholarship (Class 9–10)", nameHindi: "अनुसूचित जाति प्री-मैट्रिक छात्रवृत्ति (कक्षा 9-10)", description: "Scholarship for SC students studying in classes 9 and 10.", descriptionHindi: "कक्षा 9 और 10 में पढ़ने वाले एससी छात्रों के लिए छात्रवृत्ति।", schemeType: "scholarship", category: "sc", minAge: 14, maxAge: 20, maxIncome: 200000, ministry: "Ministry of Social Justice and Empowerment", benefitAmount: "Rs. 150–350 per month + book allowance", applicationUrl: "https://scholarships.gov.in", documents: ["Aadhar Card", "Caste Certificate", "Income Certificate", "Previous Class Marksheet"], isActive: true },
      { name: "Antyodaya Anna Yojana (AAY)", nameHindi: "अंत्योदय अन्न योजना", description: "Special food scheme targeting the poorest of the poor with 35 kg of food grains per month.", descriptionHindi: "सबसे गरीब लोगों को 35 किग्रा खाद्यान्न प्रति माह प्रदान करने वाली विशेष खाद्य योजना।", schemeType: "food", category: "all", minAge: null, maxAge: null, maxIncome: 80000, ministry: "Ministry of Consumer Affairs, Food and Public Distribution", benefitAmount: "35 kg food grains per month at highly subsidized rates", applicationUrl: null, documents: ["AAY Ration Card", "Aadhar Card", "BPL Certificate"], isActive: true },
      { name: "PM Awas Yojana – SC/ST Special Component", nameHindi: "प्रधानमंत्री आवास योजना – एससी/एसटी विशेष घटक", description: "Additional housing assistance for SC/ST households under PMAY with higher subsidy and priority allotment.", descriptionHindi: "एससी/एसटी परिवारों के लिए PMAY के अंतर्गत उच्च सब्सिडी और प्राथमिकता आवंटन के साथ अतिरिक्त आवास सहायता।", schemeType: "housing", category: "sc", minAge: 18, maxAge: null, maxIncome: 200000, ministry: "Ministry of Rural Development", benefitAmount: "Up to Rs. 1,20,000 + additional State component", applicationUrl: "https://pmayg.nic.in", documents: ["Aadhar Card", "Caste Certificate", "BPL Certificate", "Land Records"], isActive: true },
      { name: "Tribal Eklavya Model Residential Schools", nameHindi: "जनजातीय एकलव्य मॉडल आवासीय विद्यालय", description: "Free quality residential education for ST students from classes 6–12.", descriptionHindi: "कक्षा 6-12 के एसटी छात्रों के लिए मुफ्त गुणवत्तापूर्ण आवासीय शिक्षा।", schemeType: "scholarship", category: "st", minAge: 10, maxAge: 18, maxIncome: null, ministry: "Ministry of Tribal Affairs", benefitAmount: "Free boarding, lodging, education and uniforms", applicationUrl: "https://emrs.tribal.gov.in", documents: ["Aadhar Card", "Tribal Certificate", "Previous Class Marksheet", "Birth Certificate"], isActive: true },
      { name: "National Family Benefit Scheme (NFBS)", nameHindi: "राष्ट्रीय पारिवारिक लाभ योजना", description: "One-time lump sum assistance of Rs. 20,000 to bereaved BPL families when the primary breadwinner dies.", descriptionHindi: "प्राथमिक कमाने वाले की मृत्यु पर बीपीएल परिवारों को Rs. 20,000 की एकमुश्त सहायता।", schemeType: "other", category: "all", minAge: null, maxAge: null, maxIncome: 100000, ministry: "Ministry of Rural Development", benefitAmount: "Rs. 20,000 one-time grant", applicationUrl: "https://nsap.nic.in", documents: ["Aadhar Card", "Death Certificate of Breadwinner", "BPL Certificate", "Bank Account Details"], isActive: true },
      { name: "PM Ujjwala Yojana 2.0", nameHindi: "प्रधानमंत्री उज्ज्वला योजना 2.0", description: "Expanded version targeting migrant workers with deposit-free LPG connections with first refill and hotplate free of cost.", descriptionHindi: "प्रवासी मजदूरों को लक्षित PMUY का विस्तारित संस्करण।", schemeType: "other", category: "women", minAge: 18, maxAge: null, maxIncome: 150000, ministry: "Ministry of Petroleum and Natural Gas", benefitAmount: "Free LPG connection + 1st refill + hotplate", applicationUrl: "https://pmuy.gov.in", documents: ["Aadhar Card", "Self-Declaration (for migrants)", "Bank Account Details"], isActive: true },
    ];

    for (const s of schemes) {
      await db.insert(schemesTable).values(s);
    }
    logger.info(`Inserted ${schemes.length} schemes`);

    const jobs = [
      { title: "Construction Laborer", organization: "Delhi PWD Contractors", category: "daily_wage", description: "General construction work including mixing cement, carrying materials, basic masonry assistance at government construction sites in Delhi.", location: "ITO, Central Delhi", city: "New Delhi", state: "Delhi", salaryRange: "Rs. 500–700 per day", contactPerson: "Ramesh Kumar (Site Supervisor)", contactPhone: "011-23456789", requirements: ["Physical fitness", "Willingness to work outdoors", "No formal education required"], isActive: true },
      { title: "Municipal Sweeper / Sanitation Worker", organization: "Municipal Corporation of Delhi", category: "government", description: "Maintaining cleanliness in assigned ward areas, sweeping roads, collecting household garbage, and disposing of waste at designated sites.", location: "Shahdara Ward", city: "New Delhi", state: "Delhi", salaryRange: "Rs. 18,000–22,000 per month", contactPerson: "Ward Officer", contactPhone: "011-22220011", requirements: ["Age 18–35", "Domicile of Delhi", "Class 8 pass"], isActive: true },
      { title: "Cook / Helper at NGO Kitchen", organization: "Sikh Gurudwara Langar Service", category: "ngo", description: "Assist in preparing and distributing free meals to 1000+ daily visitors.", location: "Bangla Sahib, Connaught Place", city: "New Delhi", state: "Delhi", salaryRange: "Rs. 12,000–15,000 per month + meals", contactPerson: "Seva Coordinator", contactPhone: "011-23740184", requirements: ["Basic cooking skills", "Able to stand for long hours", "Good hygiene habits"], isActive: true },
      { title: "Security Guard", organization: "G4S Security Services", category: "unskilled", description: "24x7 guard duty at commercial/residential complex. Day and night shifts available.", location: "Cyber City, Gurugram", city: "Gurugram", state: "Haryana", salaryRange: "Rs. 14,000–16,000 per month", contactPerson: "HR Department", contactPhone: "0124-4567890", requirements: ["Age 18–40", "Class 10 pass", "Physical fitness", "Ex-servicemen preferred"], isActive: true },
      { title: "Electrician (ITI Holder)", organization: "L&T Construction", category: "skilled", description: "Wiring installation, maintenance, and repair at construction sites.", location: "Powai Industrial Area", city: "Mumbai", state: "Maharashtra", salaryRange: "Rs. 25,000–35,000 per month", contactPerson: "Site Engineer", contactPhone: "022-67891234", requirements: ["ITI in Electrician trade", "2+ years experience", "Knowledge of safety norms"], isActive: true },
      { title: "Plumber", organization: "Shapoorji Pallonji", category: "skilled", description: "Installation and maintenance of plumbing systems in residential construction project.", location: "Thane West", city: "Mumbai", state: "Maharashtra", salaryRange: "Rs. 22,000–30,000 per month", contactPerson: "Suresh Patil", contactPhone: "022-25678901", requirements: ["Experience in plumbing", "Knowledge of pipe fitting", "Physical fitness"], isActive: true },
      { title: "NGO Field Worker – Livelihood", organization: "Pratham India Foundation", category: "ngo", description: "Community mobilization and livelihood support for urban slum residents.", location: "Dharavi", city: "Mumbai", state: "Maharashtra", salaryRange: "Rs. 18,000–22,000 per month", contactPerson: "Programme Manager", contactPhone: "022-23456789", requirements: ["Graduate in any stream", "Local language skills (Marathi/Hindi)", "Passion for community work"], isActive: true },
      { title: "Factory Worker – Textile (Weaver)", organization: "Arvind Mills", category: "skilled", description: "Operating weaving machines for denim and cotton fabric production.", location: "Naroda Industrial Estate", city: "Ahmedabad", state: "Gujarat", salaryRange: "Rs. 13,000–18,000 per month", contactPerson: "HR Manager", contactPhone: "079-22201234", requirements: ["Minimum Class 8", "Manual dexterity", "Can sit and work for long hours"], isActive: true },
      { title: "Machine Operator – Garment Factory", organization: "Orient Craft Ltd", category: "skilled", description: "Sewing machine operator for export garment manufacturing.", location: "IMT Manesar", city: "Gurugram", state: "Haryana", salaryRange: "Rs. 12,000–16,000 per month + OT", contactPerson: "Production Manager", contactPhone: "0124-2345678", requirements: ["Experience on sewing machine", "Speed of 40+ pieces/hour", "Minimum Class 5"], isActive: true },
      { title: "Agricultural Laborer – Paddy Harvesting", organization: "Progressive Farmers Collective", category: "daily_wage", description: "Seasonal paddy harvesting in Amritsar district farms.", location: "Majitha Road", city: "Amritsar", state: "Punjab", salaryRange: "Rs. 450–600 per day + accommodation", contactPerson: "Farm Manager", contactPhone: "0183-2345678", requirements: ["Physical fitness", "Experience in farm labor preferred", "Willing to relocate temporarily"], isActive: true },
      { title: "Data Entry Operator", organization: "Chandigarh e-Governance Society", category: "government", description: "Entering citizen data into government databases, scanning documents.", location: "Sector 17, UT Secretariat", city: "Chandigarh", state: "Punjab", salaryRange: "Rs. 15,000–18,000 per month", contactPerson: "Project Manager", contactPhone: "0172-2700222", requirements: ["Class 12 with computer certificate", "Typing speed 30 WPM", "Knowledge of MS Office"], isActive: true },
      { title: "Masonry Worker / Mason", organization: "Housing Board Haryana", category: "daily_wage", description: "Construction of boundary walls, rooms, and laying bricks for government housing projects.", location: "Sector 18, Faridabad", city: "Faridabad", state: "Haryana", salaryRange: "Rs. 700–900 per day", contactPerson: "Junior Engineer", contactPhone: "0129-2345678", requirements: ["3+ years masonry experience", "Can read basic plans", "Own tools preferred"], isActive: true },
      { title: "Auto-Rickshaw Driver (Permit Holder)", organization: "Ola / Rapido Partner Network", category: "daily_wage", description: "Drive auto-rickshaw on app-based platform. Flexible working hours.", location: "Koramangala Hub", city: "Bengaluru", state: "Karnataka", salaryRange: "Rs. 20,000–35,000 per month (earnings vary)", contactPerson: "Onboarding Officer", contactPhone: "080-46563333", requirements: ["Valid driving license (LMV)", "Auto-rickshaw permit", "Smart phone"], isActive: true },
      { title: "Housekeeping Staff", organization: "Manipal Hospitals", category: "unskilled", description: "Cleaning and sanitation of hospital wards, OPD areas, corridors.", location: "HAL Airport Road", city: "Bengaluru", state: "Karnataka", salaryRange: "Rs. 13,000–16,000 per month", contactPerson: "HR – Housekeeping", contactPhone: "080-25023300", requirements: ["Class 8 pass", "Physical fitness", "Willingness to work in hospital environment"], isActive: true },
      { title: "Community Health Worker – ASHA", organization: "Karnataka Health Department", category: "government", description: "Serve as first point of contact between community and health system.", location: "Rural PHC", city: "Mysuru", state: "Karnataka", salaryRange: "Rs. 6,000–8,000 per month + incentives", contactPerson: "Block Medical Officer", contactPhone: "0821-2345678", requirements: ["Female candidate", "Resident of the village", "Class 8 pass", "Age 25–45"], isActive: true },
      { title: "Painter (Industrial)", organization: "Tata Motors Plant", category: "skilled", description: "Painting and coating of vehicle bodies in automobile manufacturing plant.", location: "Pimpri-Chinchwad", city: "Pune", state: "Maharashtra", salaryRange: "Rs. 20,000–26,000 per month", contactPerson: "Shop Floor Supervisor", contactPhone: "020-27473100", requirements: ["ITI in Painter trade or 3+ years experience", "Knowledge of industrial paints", "Safety awareness"], isActive: true },
      { title: "Domestic Helper / Cook", organization: "Urban Company (Urban Clap)", category: "unskilled", description: "Work as domestic helper and cook in homes. Part-time and full-time options.", location: "Baner / Aundh Area", city: "Pune", state: "Maharashtra", salaryRange: "Rs. 12,000–20,000 per month", contactPerson: "Placement Coordinator", contactPhone: "1800-208-1234", requirements: ["Cooking skills (North/South Indian)", "References required", "Age 25–50"], isActive: true },
      { title: "Welding Technician", organization: "Bharat Heavy Electricals Ltd (BHEL)", category: "skilled", description: "MIG/TIG welding on heavy electrical equipment, turbine components.", location: "BHEL Haridwar Township", city: "Haridwar", state: "Uttarakhand", salaryRange: "Rs. 28,000–38,000 per month", contactPerson: "Technical Recruitment Cell", contactPhone: "01334-224000", requirements: ["ITI Welder + ASME/AWS certification preferred", "3+ years in heavy fabrication", "Safety knowledge"], isActive: true },
      { title: "Rickshaw Puller (e-Rickshaw)", organization: "Delhi e-Rickshaw Association", category: "daily_wage", description: "Operate e-rickshaw on fixed route near metro stations.", location: "Janakpuri West Metro Station", city: "New Delhi", state: "Delhi", salaryRange: "Rs. 500–900 per day (self-employed)", contactPerson: "Association Secretary", contactPhone: "011-29879876", requirements: ["Valid driving license", "Age 18–55", "Initial deposit of Rs. 5,000–10,000"], isActive: true },
      { title: "Anganwadi Worker / Helper", organization: "Integrated Child Development Services (ICDS)", category: "government", description: "Provide early childhood care including nutrition, pre-school education, health check-ups.", location: "Bhandup East", city: "Mumbai", state: "Maharashtra", salaryRange: "Rs. 7,000–10,000 per month", contactPerson: "Child Development Project Officer", contactPhone: "022-25923030", requirements: ["Female candidate, resident of area", "Age 21–45", "Class 10 pass", "Local language fluency"], isActive: true },
      { title: "Cobbler / Footwear Repair (Artisan)", organization: "PM Vishwakarma Beneficiary Program", category: "skilled", description: "Traditional cobbler seeking skill upgrade under PM Vishwakarma scheme.", location: "Karol Bagh Market", city: "New Delhi", state: "Delhi", salaryRange: "Rs. 15,000–25,000 per month (self-employed)", contactPerson: "Skill India Center", contactPhone: "011-23490101", requirements: ["Traditional cobbler/footwear repair experience", "Aadhar registration", "Apply under PM Vishwakarma scheme"], isActive: true },
      { title: "Nurse / ANM (Auxiliary Nurse Midwife)", organization: "Government Medical College & Hospital", category: "government", description: "Provide nursing care in Kolkata district hospital.", location: "Shyambazar", city: "Kolkata", state: "West Bengal", salaryRange: "Rs. 22,000–28,000 per month", contactPerson: "Nursing Superintendent", contactPhone: "033-25551234", requirements: ["GNM / ANM Certificate", "State NMC Registration", "Experience preferred"], isActive: true },
      { title: "Loaders / Unloaders – Wholesale Market", organization: "Koley Market Committee", category: "daily_wage", description: "Daily loading and unloading at Kolkata's Koley wholesale market.", location: "Central Avenue, Shyambazar", city: "Kolkata", state: "West Bengal", salaryRange: "Rs. 400–600 per day", contactPerson: "Market Supervisor", contactPhone: "033-25678901", requirements: ["Physical strength", "Age 18–45", "Can work early morning shifts"], isActive: true },
      { title: "District Level NGO Coordinator", organization: "CRY (Child Rights and You)", category: "ngo", description: "Coordinate child rights programs, manage community mobilizers in Jaipur district.", location: "Vaishali Nagar", city: "Jaipur", state: "Rajasthan", salaryRange: "Rs. 22,000–28,000 per month", contactPerson: "Regional HR Manager", contactPhone: "0141-2765432", requirements: ["Graduate + 2 years NGO experience", "Hindi proficiency essential", "Two-wheeler mandatory"], isActive: true },
      { title: "Tailor / Garment Stitching", organization: "Jaipur Artisan Cooperative", category: "skilled", description: "Stitching of traditional Rajasthani garments and export-quality kurtis.", location: "Sanganer Road", city: "Jaipur", state: "Rajasthan", salaryRange: "Rs. 10,000–20,000 per month (piece-rate)", contactPerson: "Cooperative Manager", contactPhone: "0141-2345678", requirements: ["Sewing machine operation", "Stitching speed and accuracy", "Home-based work possible"], isActive: true },
      { title: "Solid Waste Management Worker", organization: "Lucknow Municipal Corporation", category: "government", description: "Door-to-door garbage collection with cycle tricycle.", location: "Gomtinagar Ward", city: "Lucknow", state: "Uttar Pradesh", salaryRange: "Rs. 13,000–16,000 per month", contactPerson: "Sanitation Inspector", contactPhone: "0522-2234567", requirements: ["Class 8 pass", "UP Domicile", "Age 18–35"], isActive: true },
      { title: "School Midday Meal Cook", organization: "Akshaya Patra Foundation", category: "ngo", description: "Cooking nutritious midday meals for 10,000+ school children daily.", location: "Vrindavan Kitchen Hub", city: "Mathura", state: "Uttar Pradesh", salaryRange: "Rs. 10,000–13,000 per month", contactPerson: "Kitchen Manager", contactPhone: "0565-2410055", requirements: ["Cooking skills", "Physical fitness", "Food safety awareness", "Age 25–50"], isActive: true },
      { title: "Pump Operator / Irrigation Worker", organization: "Haryana Irrigation Department", category: "government", description: "Operate canal and tubwell irrigation pumps, maintain flow logs.", location: "Sirsa Canal Division", city: "Sirsa", state: "Haryana", salaryRange: "Rs. 16,000–20,000 per month", contactPerson: "SDO Irrigation", contactPhone: "01666-223456", requirements: ["Class 10 pass", "Basic knowledge of pumps", "Haryana Domicile"], isActive: true },
      { title: "Fisherman / Fishing Boat Worker", organization: "Tamil Nadu Fishermen Cooperative", category: "daily_wage", description: "Sea fishing work in Bay of Bengal using mechanized fishing boats.", location: "Kasimedu Fish Harbour", city: "Chennai", state: "Tamil Nadu", salaryRange: "Rs. 500–1200 per day (share basis)", contactPerson: "Cooperative Office", contactPhone: "044-25930123", requirements: ["Fishing experience", "Sea-worthy fitness", "Safety training preferred"], isActive: true },
      { title: "Handloom Weaver", organization: "Pochampally Handloom Weavers Society", category: "skilled", description: "Traditional Ikat handloom weaving for Pochampally silk sarees.", location: "Bhoodan Pochampally", city: "Hyderabad", state: "Telangana", salaryRange: "Rs. 12,000–25,000 per month (piece-rate)", contactPerson: "Society Manager", contactPhone: "040-24501234", requirements: ["Weaving experience preferred", "Training for new weavers available", "Age 18–55"], isActive: true },
      { title: "Delivery Partner", organization: "Amazon Flex / Swiggy Gig", category: "daily_wage", description: "Last-mile delivery of packages/food orders. Flexible shifts.", location: "Kondapur Hub", city: "Hyderabad", state: "Telangana", salaryRange: "Rs. 15,000–25,000 per month", contactPerson: "Gig Onboarding Team", contactPhone: "1800-419-7355", requirements: ["Own two-wheeler", "Valid driving license", "Smart phone", "Age 18–40"], isActive: true },
      { title: "ASHA Facilitator / Block Coordinator", organization: "Bihar Health Department (NHM)", category: "government", description: "Supervise 20–25 ASHA workers in a block, conduct training, verify reports.", location: "Danapur Block", city: "Patna", state: "Bihar", salaryRange: "Rs. 15,000–18,000 per month", contactPerson: "Block Programme Manager", contactPhone: "0612-2234567", requirements: ["Female candidate", "Class 12 pass", "Age 25–45", "ASHA experience preferred"], isActive: true },
      { title: "Forest Guard / Van Rakshak", organization: "Madhya Pradesh Forest Department", category: "government", description: "Patrol forest areas, prevent illegal logging and poaching.", location: "Kanha Forest Range", city: "Balaghat", state: "Madhya Pradesh", salaryRange: "Rs. 18,000–22,000 per month", contactPerson: "Range Forest Officer", contactPhone: "07632-234567", requirements: ["Class 12 pass", "Physical fitness (5 km run in 25 mins)", "MP Domicile", "Age 18–35"], isActive: true },
      { title: "Brick Kiln Worker", organization: "Rajkot Brick Manufacturers Association", category: "daily_wage", description: "Making, drying, and stacking bricks at brick kiln. Seasonal work.", location: "Aji GIDC Road", city: "Rajkot", state: "Gujarat", salaryRange: "Rs. 350–500 per day + accommodation", contactPerson: "Kiln Owner", contactPhone: "0281-2345678", requirements: ["Physical fitness", "No formal education required", "Family housing available"], isActive: true },
      { title: "Hospital Attendant / Ward Boy", organization: "King George's Medical University", category: "unskilled", description: "Patient care assistance including shifting on stretchers, bed making.", location: "Chowk, KGMU Campus", city: "Lucknow", state: "Uttar Pradesh", salaryRange: "Rs. 12,000–15,000 per month", contactPerson: "Nursing Superintendent", contactPhone: "0522-2258800", requirements: ["Class 10 pass", "Age 18–35", "Ability to handle patients with care", "Physical fitness"], isActive: true },
    ];

    for (const j of jobs) {
      await db.insert(jobsTable).values(j);
    }
    logger.info(`Inserted ${jobs.length} jobs`);

    const centers = [
      { name: "Goonj NGO – Delhi", type: "ngo", address: "J-93, Sarita Vihar", city: "New Delhi", state: "Delhi", phone: "011-26972351", email: "mail@goonj.org", services: ["Clothing distribution", "Disaster relief", "Urban-rural material transfer"], operatingHours: "Mon–Sat: 9 AM – 6 PM", isActive: true },
      { name: "Pratham India Foundation", type: "ngo", address: "Y-9, Hauz Khas", city: "New Delhi", state: "Delhi", phone: "011-41006000", email: "info@pratham.org", services: ["Child education", "Dropout prevention", "Vocational training", "Adult literacy"], operatingHours: "Mon–Fri: 9 AM – 5 PM", isActive: true },
      { name: "AIIMS Delhi (Emergency)", type: "hospital", address: "Sri Aurobindo Marg, Ansari Nagar", city: "New Delhi", state: "Delhi", phone: "011-26588500", email: "director@aiims.edu", services: ["Emergency care", "OPD (free for BPL)", "ICU", "Cancer treatment", "Trauma care"], operatingHours: "24x7 Emergency; OPD: Mon–Sat 8 AM – 1 PM", isActive: true },
      { name: "Safdarjung Hospital", type: "hospital", address: "Ring Road, Ansari Nagar West", city: "New Delhi", state: "Delhi", phone: "011-26707444", email: "safdarjung@nic.in", services: ["General medicine", "Surgery", "Maternity", "Pediatrics", "Burns"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Annapoorna Food Bank – Delhi", type: "food_center", address: "Plot 7, Laxmi Nagar Industrial Area", city: "New Delhi", state: "Delhi", phone: "011-22450983", email: "annapoorna@gmail.com", services: ["Free meals", "Ration distribution", "Hunger helpline", "Festival food drives"], operatingHours: "Daily: 12 PM – 2 PM and 7 PM – 9 PM", isActive: true },
      { name: "Roti Bank Delhi", type: "food_center", address: "15-B, Kalkaji Extension", city: "New Delhi", state: "Delhi", phone: "011-26293029", email: "rotibank.del@gmail.com", services: ["Free meals to homeless", "Night shelters food", "Emergency food packs"], operatingHours: "Daily: 8 PM – 10 PM (street distribution)", isActive: true },
      { name: "Udayan Care", type: "ngo", address: "K-4/17, Hauz Khas Enclave", city: "New Delhi", state: "Delhi", phone: "011-26510632", email: "info@udayancare.org", services: ["Orphan care", "Girl empowerment", "Scholarship", "Vocational training"], operatingHours: "Mon–Fri: 9 AM – 5 PM", isActive: true },
      { name: "Ketto Foundation (Fund Support)", type: "ngo", address: "Ackruti Star, MIDC, Andheri East", city: "Mumbai", state: "Maharashtra", phone: "022-49200000", email: "support@ketto.org", services: ["Medical crowdfunding", "Cancer treatment support", "Medical emergency relief"], operatingHours: "Mon–Fri: 9 AM – 7 PM", isActive: true },
      { name: "KEM Hospital", type: "hospital", address: "Acharya Donde Marg, Parel", city: "Mumbai", state: "Maharashtra", phone: "022-24107000", email: "kemhospital@brihanmumbai.gov.in", services: ["Free treatment for BPL", "Emergency", "Trauma", "Cancer", "Pediatrics"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Roti Bank Mumbai", type: "food_center", address: "Near CSMT Station, Boria Bunder", city: "Mumbai", state: "Maharashtra", phone: "022-22656060", email: "rotibank.mumbai@gmail.com", services: ["Hot meals for homeless", "Tiffin service for daily wagers", "Night food distribution"], operatingHours: "Daily: 7 PM – 9 PM", isActive: true },
      { name: "Smile Foundation", type: "ngo", address: "2nd Floor, Shiv Sena Bhavan, Worli", city: "Mumbai", state: "Maharashtra", phone: "022-67474747", email: "mumbai@smilefoundationindia.org", services: ["Child education", "Health camps", "Women empowerment", "Vocational training"], operatingHours: "Mon–Sat: 10 AM – 6 PM", isActive: true },
      { name: "Lokmanya Tilak Municipal General Hospital", type: "hospital", address: "Dr. Babasaheb Ambedkar Road, Sion", city: "Mumbai", state: "Maharashtra", phone: "022-24071000", email: "sionhospital@bmc.gov.in", services: ["Free BPL treatment", "Trauma", "Burns", "Psychiatric care", "Maternity"], operatingHours: "OPD: Mon–Sat 7:30 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Akshaya Patra Foundation – Mumbai", type: "food_center", address: "Plot 128, MIDC, Mahape, Navi Mumbai", city: "Navi Mumbai", state: "Maharashtra", phone: "022-27782248", email: "mumbai@akshayapatra.org", services: ["School midday meals", "Disaster relief food", "Community food distribution"], operatingHours: "Kitchen: 4 AM – 12 PM", isActive: true },
      { name: "Smile Foundation – Bangalore", type: "ngo", address: "15/1, Double Road, Indiranagar", city: "Bengaluru", state: "Karnataka", phone: "080-25221234", email: "bangalore@smilefoundationindia.org", services: ["Child education", "Health camps", "Women skill training"], operatingHours: "Mon–Sat: 9 AM – 6 PM", isActive: true },
      { name: "Victoria Hospital", type: "hospital", address: "Fort Road, Fort", city: "Bengaluru", state: "Karnataka", phone: "080-22867851", email: "victoria@bmcri.org", services: ["Free OPD for poor", "Emergency", "Burns unit", "Orthopedics"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Rajiv Gandhi Institute of Chest Diseases", type: "hospital", address: "Hosur Road, Hombegowda Nagar", city: "Bengaluru", state: "Karnataka", phone: "080-26631621", email: "rgicd@gmail.com", services: ["Tuberculosis treatment (free)", "Chest diseases", "Respiratory care", "DOTS therapy"], operatingHours: "Mon–Sat: 8 AM – 12:30 PM", isActive: true },
      { name: "The Akshaya Patra Foundation – Bengaluru", type: "food_center", address: "Sri Radha Madanmohan Temple Campus, Rajajinagar", city: "Bengaluru", state: "Karnataka", phone: "080-23606788", email: "info@akshayapatra.org", services: ["School midday meals", "Community meals", "Festival food"], operatingHours: "Kitchen 4 AM – 12 PM", isActive: true },
      { name: "ISKON Food for Life – Bengaluru", type: "food_center", address: "Hare Krishna Hill, Chord Road", city: "Bengaluru", state: "Karnataka", phone: "080-23473737", email: "iskconblr@gmail.com", services: ["Free prasadam distribution", "Relief food in disasters", "Feast for homeless"], operatingHours: "Daily: Sunday feast 12 PM – 3 PM; Daily prasadam 12 PM – 1 PM", isActive: true },
      { name: "Government General Hospital Chennai", type: "hospital", address: "Park Town, Park Road", city: "Chennai", state: "Tamil Nadu", phone: "044-25305000", email: "gghosp@tn.gov.in", services: ["Emergency (free)", "Cancer treatment", "Organ transplant", "Free healthcare for BPL"], operatingHours: "OPD: Mon–Sat 8 AM – 12 PM; Emergency 24x7", isActive: true },
      { name: "Stanley Medical College Hospital", type: "hospital", address: "Old Jail Road, Royapuram", city: "Chennai", state: "Tamil Nadu", phone: "044-25212345", email: "stanley@tnmedical.com", services: ["Free for BPL patients", "Surgery", "Gynecology", "Pediatrics"], operatingHours: "OPD: Mon–Sat 7:30 AM – 12 PM; Emergency 24x7", isActive: true },
      { name: "Bread for the Poor Foundation", type: "food_center", address: "27, Poonamallee Road, Egmore", city: "Chennai", state: "Tamil Nadu", phone: "044-26644567", email: "bfpfoundation@gmail.com", services: ["Free meals daily", "Ration kits for BPL families", "Old age home support"], operatingHours: "Daily: 12 PM and 7 PM", isActive: true },
      { name: "CRY – Child Rights and You (South)", type: "ngo", address: "No. 4, Canal Road, Opposite PTC Depot, Saidapet", city: "Chennai", state: "Tamil Nadu", phone: "044-24357170", email: "cry.south@cry.org", services: ["Child rights advocacy", "School enrollment drives", "Child labor prevention"], operatingHours: "Mon–Fri: 9 AM – 5 PM", isActive: true },
      { name: "SSKM Hospital (PG Hospital)", type: "hospital", address: "244, AJC Bose Road, Bhowanipore", city: "Kolkata", state: "West Bengal", phone: "033-22041904", email: "sskm@gmail.com", services: ["Comprehensive free care", "Transplant", "Cardiology", "Neurosurgery", "Cancer"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Missionaries of Charity – Mother House", type: "ngo", address: "54A, AJC Bose Road, Rambagan", city: "Kolkata", state: "West Bengal", phone: "033-22497115", email: null, services: ["Destitute and dying care", "Orphan care", "Leprosy care", "Free meals"], operatingHours: "Mon–Sat: 8 AM – 12 PM and 3 PM – 5 PM", isActive: true },
      { name: "Food Bank Kolkata – Rajasthani Seva Samiti", type: "food_center", address: "22/1 Marquis Street", city: "Kolkata", state: "West Bengal", phone: "033-22658763", email: "rajseva.kol@gmail.com", services: ["Free meals for homeless", "Ration distribution", "Old age support"], operatingHours: "Daily: 11 AM – 1 PM", isActive: true },
      { name: "Gandhi Hospital Hyderabad", type: "hospital", address: "Gandhi Hospital Road, Musheerabad", city: "Hyderabad", state: "Telangana", phone: "040-27505566", email: "gandhi.hosp@telangana.gov.in", services: ["Free emergency care", "Burn treatment", "Trauma", "Maternity"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Udyama NGO Hyderabad", type: "ngo", address: "5-4-187, Bank Street, Koti", city: "Hyderabad", state: "Telangana", phone: "040-24752345", email: "udyama@gmail.com", services: ["Livelihood training", "Women self-help groups", "Tribal welfare"], operatingHours: "Mon–Fri: 9 AM – 5 PM", isActive: true },
      { name: "Zindagi Foundation – Food for All", type: "food_center", address: "Mehdipatnam Road, Tolichowki", city: "Hyderabad", state: "Telangana", phone: "040-23543210", email: "zindagi@foodforall.in", services: ["Free meals for construction workers", "Ration kits for migrant families", "Night shelters"], operatingHours: "Daily: 12 PM and 7 PM", isActive: true },
      { name: "Sassoon General Hospital Pune", type: "hospital", address: "Jai Prakash Narayan Road, Near Station", city: "Pune", state: "Maharashtra", phone: "020-26127000", email: "sassoon@gmail.com", services: ["Free BPL treatment", "Emergency", "Orthopedics", "Obstetrics", "General surgery"], operatingHours: "OPD: Mon–Sat 8 AM – 12 PM; Emergency 24x7", isActive: true },
      { name: "Savitribai Phule Pune Foundation", type: "ngo", address: "47, Erandawana", city: "Pune", state: "Maharashtra", phone: "020-25455678", email: "sppfoundation@gmail.com", services: ["Women education", "Dalit empowerment", "Child care centers"], operatingHours: "Mon–Fri: 10 AM – 5 PM", isActive: true },
      { name: "Robin Hood Army – Pune Chapter", type: "food_center", address: "Koregaon Park", city: "Pune", state: "Maharashtra", phone: null, email: "pune@robinhoodarmy.com", services: ["Weekend food drives", "Surplus food redistribution", "Festival meals for homeless"], operatingHours: "Weekends: 7 PM – 9 PM (varies)", isActive: true },
      { name: "SMS Hospital Jaipur", type: "hospital", address: "JLN Marg, Near New Gate", city: "Jaipur", state: "Rajasthan", phone: "0141-2518501", email: "sms.hosp@rajasthan.gov.in", services: ["Free treatment under Chiranjeevi scheme", "Emergency", "Trauma", "Cancer", "Orthopedics"], operatingHours: "OPD: Mon–Sat 8 AM – 12 PM; Emergency 24x7", isActive: true },
      { name: "Seva Mandir Udaipur", type: "ngo", address: "Old Fatehpura, Udaipur", city: "Udaipur", state: "Rajasthan", phone: "0294-2450960", email: "mail@sevamandir.org", services: ["Tribal development", "Rural health", "Women empowerment", "Natural resource management"], operatingHours: "Mon–Sat: 9 AM – 5 PM", isActive: true },
      { name: "Annapurna Seva Samiti – Jaipur", type: "food_center", address: "Lal Kothi, Tonk Road", city: "Jaipur", state: "Rajasthan", phone: "0141-2740234", email: null, services: ["Daily langar (free meals)", "Ration distribution on festivals", "Winter blanket distribution"], operatingHours: "Daily: 12 PM – 2 PM and 8 PM – 9 PM", isActive: true },
      { name: "Dr. Ram Manohar Lohia Institute", type: "hospital", address: "Vibhuti Khand, Gomti Nagar", city: "Lucknow", state: "Uttar Pradesh", phone: "0522-2495500", email: "drmli@up.gov.in", services: ["Free specialist care", "Neurology", "Cardiology", "Cancer", "Dialysis (free for BPL)"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Bal Vikas Sewa Samiti", type: "ngo", address: "10, Indira Nagar Colony, Sector B", city: "Lucknow", state: "Uttar Pradesh", phone: "0522-2346789", email: "bvsslko@gmail.com", services: ["Street children rehabilitation", "Education for underprivileged", "Child labor rescue"], operatingHours: "Mon–Sat: 9 AM – 5 PM", isActive: true },
      { name: "Guru Ka Langar – Lucknow", type: "food_center", address: "Sector C, Aliganj Gurudwara", city: "Lucknow", state: "Uttar Pradesh", phone: "0522-2330055", email: null, services: ["Free langar daily", "Ration support for migrants", "Langar for hospital attendants"], operatingHours: "Daily: 12 PM – 3 PM and 7 PM – 9 PM", isActive: true },
      { name: "Patna Medical College Hospital (PMCH)", type: "hospital", address: "Ashok Rajpath, Bankipore", city: "Patna", state: "Bihar", phone: "0612-2300248", email: "pmch@gmail.com", services: ["Free BPL treatment", "Emergency", "Maternity", "Pediatrics", "General surgery"], operatingHours: "OPD: Mon–Sat 8 AM – 12 PM; Emergency 24x7", isActive: true },
      { name: "Sahyogi NGO – Bihar", type: "ngo", address: "Boring Road, Near Exhibition Ground", city: "Patna", state: "Bihar", phone: "0612-2567890", email: "sahyogi.bihar@gmail.com", services: ["Migrant worker support", "Legal aid", "Ration card facilitation", "Shelter referrals"], operatingHours: "Mon–Sat: 9 AM – 5 PM", isActive: true },
      { name: "Bihar Food Bank Initiative", type: "food_center", address: "Raj Bhavan Road, Kumhrar", city: "Patna", state: "Bihar", phone: "0612-2234098", email: null, services: ["Free meals for homeless", "Dry ration distribution", "Flood relief food"], operatingHours: "Daily: 12 PM – 2 PM", isActive: true },
      { name: "Civil Hospital Ahmedabad", type: "hospital", address: "Asarwa, Medical Education & Research", city: "Ahmedabad", state: "Gujarat", phone: "079-22681040", email: "civil.ahmedabad@gmail.com", services: ["Free treatment for all", "Cancer (GCRI)", "Burns", "Trauma", "1200+ beds"], operatingHours: "OPD: Mon–Sat 8 AM – 1 PM; Emergency 24x7", isActive: true },
      { name: "Self Employed Women's Association (SEWA)", type: "ngo", address: "SEWA Reception Centre, Bhadra", city: "Ahmedabad", state: "Gujarat", phone: "079-25506477", email: "mail@sewa.org", services: ["Women labor rights", "Microfinance", "Skill training", "Health insurance for informal workers"], operatingHours: "Mon–Sat: 9 AM – 5 PM", isActive: true },
      { name: "Annapurna Community Kitchen – Ahmedabad", type: "food_center", address: "Raipur Darwaja, Old City", city: "Ahmedabad", state: "Gujarat", phone: "079-22163456", email: null, services: ["Rs. 5 meals for poor (state-run)", "Free meals for homeless", "Distribution at railway station"], operatingHours: "Daily: 7 AM – 9 AM and 12 PM – 2 PM", isActive: true },
    ];

    for (const c of centers) {
      await db.insert(assistanceCentersTable).values(c);
    }
    logger.info(`Inserted ${centers.length} assistance centers`);

    const activities = [
      { type: "scheme_added", title: "PM Awas Yojana (PMAY-G) Updated", description: "Housing scheme benefit amount updated to Rs. 1.30 lakh for hilly/NE states" },
      { type: "scheme_added", title: "PM Vishwakarma Yojana Added", description: "New scheme for artisans and craftspeople added with Rs. 1 lakh loan at 5% interest" },
      { type: "job_posted", title: "35 New Jobs Posted", description: "New positions added across Delhi, Mumbai, Bengaluru, Chennai, Kolkata and more cities" },
      { type: "center_added", title: "Missionaries of Charity – Kolkata Added", description: "Mother House registered as assistance center for destitute and dying care" },
      { type: "scheme_added", title: "PM Jan Dhan Yojana Data Refreshed", description: "PMJDY overdraft limit updated to Rs. 10,000 with accident cover Rs. 2 lakh" },
      { type: "center_added", title: "SEWA Ahmedabad Registered", description: "Self Employed Women's Association added as NGO assistance center for informal workers" },
    ];

    for (const a of activities) {
      await db.insert(activityTable).values(a);
    }
    logger.info(`Inserted ${activities.length} activities`);

    logger.info("Auto-seed complete: 44 schemes, 35 jobs, 43 centers, 6 activities");
  } catch (err) {
    logger.error({ err }, "Auto-seed failed");
  }
}
